# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 13:31
from __future__ import unicode_literals

from django.db import migrations
import simplemde.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160508_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=simplemde.fields.SimpleMdeField(),
        ),
    ]
